baseURL = "https://v3l1d.github.io/"
contentDir = "content"  # Content directory should be 'content' (not 'docs')
title = "v3l1d's Blog"
languageCode = "en-us"
theme = "hello-friend-ng"  # Set theme to hello-friend-ng
paginate = 10
publishDir   = "docs"

[params]
  mainSections = ["post"] 
  recentPostsLimit = 5   
  dateform = "Jan 2, 2006"
  dateformShort = "Jan 2"
  dateformNum = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
  Portrait = "/images/avatar.jpg"  # Path to your avatar (ensure it's in 'static/images/')
  homeSubtitle = "CTF Insights"
  disableReadOtherPosts = false
  enableSharingButtons = true
  hasMermaid = false
  enableGlobalLanguageMenu = false
  enableThemeToggle = true
  description = "v3l1d's Writeups Blog"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
  category = "blog"
  tag = "tags"
  series = "series"

[languages]
  [languages.en]
    title = "v3l1d's Blog"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  [languages.en.params]
    subtitle = "Cybersecurity Shares"
    [languages.en.params.logo]
      logoText = "v3l1d's blog"
      logoHomeLink = "/"

[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts"
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2
