baseURL: https://v3l1d.github.io/
languageCode: en-us
title: v3l1d's Blog
theme: mini
publishDir: docs
showToc: true
social:
  github: https://github.com/v3l1d



permalinks:
  posts: "/posts/:title/"


permalinks:
    posts: /posts/:title/

hasCJKLanguage: true

paginate: 3

mediaTypes:
  image/png:
    render: true

googleAnalytics: your-google-analytics-id
disqusShortname: your-disqus-shortname

# Hugo Configure Markup
# More info: https://gohugo.io/getting-started/configuration-markup#
markup:
  highlight:
    guessSyntax: true
    style: monokai
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
  # needed to render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
  goldmark:
    renderer:
      unsafe: true


# Site parameters
params:
  # Site Author
  author: v31ld
  # Author biography
  bio: Software Engineer, Cybersecurity graduated
  # Site Description, used in HTML meat
  description:

  tags: false

  ###########################################
  # Optional Configuration
  ###########################################

  # To enable RSS, you could set `enableRSS: true`, default is `true`
  enableRSS: false
  # To enable comments, you may need to set `disqusShortname`
  enableComments: true
  # To enable comments, you may need to set `googleAnalytics`
  enableGoogleAnalytics: false
  # To enable table of content, you could set `showToc: true`, default is `false`
  showToc: false
  # To hidden powerBy message in the page footer, you could set: `showPowerBy: false`, default is `true`
  showPowerBy: true
  # To enable math typesetting , you could set `math: true`, default is `false`
  math: false
  # To hidden post summary in home page, you could set `hiddenPostSummaryInHomePage: true`, default is `false`
  hiddenPostSummaryInHomePage: true
  # Website copyright, default: '© Copyright 2021 ❤️ {params.author}'
  copyright: '❤️ v3l1d' 
